### ISSUE TITLE
Form layout

### ISSUE THREAD

**Issue by IJNIHR** [IJNIHR/PRESapp#2]
The way the Next, Previous and Submit buttons 'bounce' about still looks clunky. Can they be placed between the tabs and the question so they are static?

**Comment by SteveErrington** [comment]
I've added extra copies of the three buttons between the tabs and the tabs items with Submit between the Previous and Next buttons (to save vertical space).

Unfortunately the Submit button jumps about when the other two are hidden at either end of the step process so we might have to rethink it's position.

**Comment by SteveErrington** [comment]
Previous and Next buttons moved to top, just under tabs, and the submit button has been left at the bottom.
All buttons have been flattened
