### ISSUE TITLE
Layout changes

### ISSUE THREAD

**Issue by SteveErrington** [IJNIHR/PRESapp#3]
- [x] HOME - Change Hints on Study/Site to explain to user how to search/select
- [x] HOME - Add CPMS ID to Study description (makes it searchable)
- [x] HOME - Change Delete option from PRES FORMS drop down to 'Edit Existing Form' current phase only with no responses
- [x] Tabbed Form - buttons PREVIOUS|spacer|NEXT| at top of question
- [x] Tabbed Form - buttons spacer|SUBMIT at bottom
- [x] Tabbed Form - Flatten question cards or merge them
- [x] Date Picker - change to vertical everywhere
- [x] Tabbed Form - change Flex to SM8
- [x] Tabbed Form - make buttons flat

**Comment by IJNIHR** [comment]
Can you make the PREVIOUS, NEXT & SUBMIT buttons a darker colour? I don't think they stand out enough now?

**Comment by SteveErrington** [comment]
Yes, I was thinking that, either that or change them to the Outline style, which will put a box round them and make them more obviously buttons.  There's a variety of button styles on the form creation screen as I was canvassing opinion from Christine and Karen on Monday.

I'll change them to dark green to see if that's better.
